version: '3.10'
name: letterbook

# Optional Dashboarding and Observability Services
services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: unless-stopped

  grafana:
    depends_on:
      - loki
      - prometheus
      - tempo
    container_name: grafana
    image: grafana/grafana-oss:11.4.0
    ports:
      - "3000:3000"
    volumes:
      - "./Letterbook.Dashboards/Grafana/provisioning:/etc/grafana/provisioning:z"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - "./Letterbook.Dashboards/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z"
    restart: unless-stopped

  tempo:
    container_name: tempo
    image: &tempo-image grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    depends_on:
      - tempo-init
    volumes:
      - ./Letterbook.Dashboards/Tempo/tempo.yaml:/etc/tempo.yaml:z
      - tempo_data:/tmp/tempo
    ports:
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
    restart: unless-stopped

  tempo-init:
    container_name: tempo-init
    image: *tempo-image
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo_data:/var/tempo
    restart: on-failure

  db_metrics_exporter:
    container_name: metrics_exporter
    image: prometheuscommunity/postgres-exporter
    depends_on:
      - timescale
      - letterbook_db
    ports:
      - 9187:9187
    volumes:
      - "./Letterbook.Dashboards/Postgres/Prometheus/postgres_exporter.yml:/postgres_exporter.yml:z"
    restart: unless-stopped

volumes:
  tempo_data:
    driver: local