version: '3.10'
name: letterbook

# Optional Dashboarding and Observability Services
services:
  loki:
    image: grafana/loki:latest
    networks:
      - default
    restart: unless-stopped

  grafana:
    depends_on:
      - loki
      - prometheus
      - tempo
    image: grafana/grafana-oss:11.4.0
    networks:
      - default
    ports:
      - "3000:3000"
    volumes:
      - "./Letterbook.Dashboards/Grafana/provisioning:/etc/grafana/provisioning:z"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.1
    networks:
      - default
    ports:
      - "9090:9090"
    volumes:
      - "./Letterbook.Dashboards/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z"
    restart: unless-stopped

  tempo:
    image: &tempo-image grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    depends_on:
      tempo-init:
        condition: service_completed_successfully
    volumes:
      - ./Letterbook.Dashboards/Tempo/tempo.yaml:/etc/tempo.yaml:z
      - tempo_data:/tmp/tempo
    networks:
      - default
    ports:
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
    restart: unless-stopped

  tempo-init:
    image: *tempo-image
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo_data:/var/tempo
    restart: on-failure

networks:
  default:
    external: true
    name: sandcastles_letterbook

volumes:
  tempo_data:
    driver: local