

services:
  # Services required for Letterbook operation
  timescale:
    container_name: timescale
    image: timescale/timescaledb:2.11.2-pg15-oss
    environment:
      - POSTGRES_USER=letterbook
      - POSTGRES_PASSWORD=letterbookpw
      - POSTGRES_DB=letterbook_feeds
    ports:
      - "5433:5432"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=letterbook
      - POSTGRES_PASSWORD=letterbookpw
      - POSTGRES_DB=letterbook
    ports:
      - "5432:5432"
    restart: always

  # Optional Dashboarding and Observability Services
  grafana:
      container_name: grafana
      image: grafana/grafana-oss:10.2.0
      ports:
        - "3000:3000"
      volumes:
        - "./Letterbook.Dashboards/Grafana/provisioning:/etc/grafana/provisioning"
        
  prometheus:
      container_name: prometheus
      image: prom/prometheus:v2.47.2
      ports:
        - "9090:9090"
      volumes:
        - "./Letterbook.Dashboards/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"