version: '3.10'
name: letterbook

services:
  # Services required for Letterbook operation
  timescale:
    container_name: timescale
    image: timescale/timescaledb:2.15.3-pg15-oss
    environment:
      - POSTGRES_USER=letterbook
      - POSTGRES_PASSWORD=letterbookpw
      - POSTGRES_DB=letterbook_feeds
    ports:
      - "5433:5432"
    volumes:
      - letterbook_ts_data:/var/lib/postgresql/data
    restart: always
  letterbook_db:
    container_name: postgres
    image: postgres:17-alpine
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=letterbook
      - POSTGRES_PASSWORD=letterbookpw
      - POSTGRES_DB=letterbook
    ports:
      - "5432:5432"
    volumes:
      - letterbook_db_data:/var/lib/postgresql/data
      - ./volumes/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always

  # Optional debug tools
  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - '8200:80'
    restart: unless-stopped

  # Optional Dashboarding and Observability Services 
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: unless-stopped
    
  grafana:    
    depends_on:
      - loki
      - prometheus
      - tempo
    container_name: grafana
    image: grafana/grafana-oss:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - "./Letterbook.Dashboards/Grafana/provisioning:/etc/grafana/provisioning"
    restart: unless-stopped
    
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.53.1
    ports:
      - "9090:9090"
    volumes:
      - "./Letterbook.Dashboards/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    
  tempo:
    container_name: tempo
    image: &tempo-image grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    depends_on:
      - tempo-init
    volumes:
      - ./Letterbook.Dashboards/Tempo/tempo.yaml:/etc/tempo.yaml
      - letterbook_tempo_data:/tmp/tempo
    ports:
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
    restart: unless-stopped

  tempo-init:
    container_name: tempo-init
    image: *tempo-image
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - letterbook_tempo_data:/var/tempo

  db_metrics_exporter:
    container_name: metrics_exporter
    image: prometheuscommunity/postgres-exporter
    depends_on:
      - timescale
      - letterbook_db
    ports:
      - 9187:9187
    volumes:
      - "./Letterbook.Dashboards/Postgres/Prometheus/postgres_exporter.yml:/postgres_exporter.yml"
    restart: unless-stopped

volumes:
  letterbook_db_data:
    driver: local
  letterbook_ts_data:
    driver: local
  letterbook_tempo_data:
    driver: local
