version: '3.10'
name: letterbook

services:
  # Services required for Letterbook operation
  timescale:
    image: timescale/timescaledb:2.17.2-pg15-oss
    environment:
      - POSTGRES_USER=letterbook
      - POSTGRES_PASSWORD=letterbookpw
      - POSTGRES_DB=letterbook_feeds
    ports:
      - "5433:5432"
    volumes:
      - ts_data:/var/lib/postgresql/data
    restart: always
  postgres:
    image: postgres:16-alpine
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=letterbook
      - POSTGRES_PASSWORD=letterbookpw
      - POSTGRES_DB=letterbook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./volumes/postgresql.conf:/etc/postgresql/postgresql.conf:z
      - ./volumes/pg_hba.conf:/etc/postgresql/pg_hba.conf:z
    restart: always

  # Optional debug tools
  httpbin:
    profiles:
      - debug
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - '8200:80'
    restart: unless-stopped


volumes:
  db_data:
    driver: local
  ts_data:
    driver: local
