GET {{host}}/actor

###
GET {{host}}/api/v1/actor

###
GET {{host}}/api/v1/accounts/11/scheduled_statuses

###
GET {{host}}/api/v1/connect/token

###
POST {{host}}/api/v1/user_account/login
accept: */*
Content-Type: application/json

{
  "email": "admin@letterbook.example",
  "password": "Password1!"
}

###
# curl -X 'POST'   'http://localhost:5127/actor/eebmU6ZHx06ezAYNia2_GA/inbox'   -H 'accept: application/ld+json'   -H 'Content-Type: application/ld+json'   -d '{
#  "type": "Follow",
#  "actor": "https://social.example/user/1"
#}'
# TODO: https://stackoverflow.com/a/62950860
POST http://localhost:5127/actor/eebmU6ZHx06ezAYNia2_GA/inbox
accept: application/ld+json
Content-Type: application/ld+json

{
  "type": "Follow",
  "actor": "https://social.example/user/1"
}

###
GET {{host}}/.well-known/webfinger?resource=acct:admin@{{host}}

###
