###
GET {{host}}/actor

###
GET {{host}}/api/v1/actor

###
GET {{host}}/api/v1/accounts/11/scheduled_statuses

###
GET {{host}}/api/v1/connect/token

###
POST {{host}}/api/v1/user_account/login
accept: */*
Content-Type: application/json

{
  "email": "admin@letterbook.example",
  "password": "Password1!"
}

###
# curl -X 'POST'   'http://localhost:5127/actor/eebmU6ZHx06ezAYNia2_GA/inbox'   -H 'accept: application/ld+json'   -H 'Content-Type: application/ld+json'   -d '{
#  "type": "Follow",
#  "actor": "https://social.example/user/1"
#}'
# TODO: https://stackoverflow.com/a/62950860
POST http://localhost:5127/actor/eebmU6ZHx06ezAYNia2_GA/inbox
accept: application/ld+json
Content-Type: application/ld+json

{
  "type": "Follow",
  "actor": "https://social.example/user/1"
}

###
GET {{host}}/.well-known/webfinger?resource=acct:admin@{{host}}

###
GET {{host}}/.well-known/webfinger?resource=acct:admin@host.docker.internal:5127

### self webfinger
GET https://{{host}}/.well-known/webfinger?resource=acct:admin@{{host}}

### self actor
GET https://{{host}}/actor/{{profile}}
Accept: application/ld+json

### peer webfinger
GET http://{{peer}}/.well-known/webfinger?resource=acct:user@{{peer}}

###
# {{profile}} can be defined in http-client.private.env.json, which is git-ignored
# That way we're not stepping on each other's local test data and creating merge conflicts
GET https://{{host}}/actor/{{profile}}#publicKey-0
Accept: application/ld+json

### debug follow
POST https://{{host}}/{{profile}}/follow
Content-Type: application/json

{
  "targetId": "http://mastodon.castle/users/user"
}

### fetch mastodon
GET https://mastodon.castle/users/user
Accept: application/ld+json

### webfinger mastodon
GET https://mastodon.castle/.well-known/webfinger?resource=acct:user@mastodon.castle

### httpbin
GET https://httpbin.castle/headers