on: [push]
jobs:
  #
  # No volume involved & the container is implicit
  #
  simple-no-container:
    runs-on: codeberg-medium
    services:
      pgsql:
        image: code.forgejo.org/oci/postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
    steps:
    - run: |
       apt-get update -qq
       apt-get install -y -qq  postgresql-client
       PGPASSWORD=postgres psql -h pgsql -U postgres -c '\dt' test
  build-and-test:
    runs-on: codeberg-medium # https://codeberg.org/actions/meta#available-runners
    services:
      timescale:
        image: timescale/timescaledb:2.17.2-pg15-oss
        environment:
          - POSTGRES_USER=letterbook
          - POSTGRES_PASSWORD=letterbookpw
          - POSTGRES_DB=letterbook_feeds
        ports:
          - "5433:5432"
      pgsql:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=letterbook
          - POSTGRES_PASSWORD=letterbookpw
          - POSTGRES_DB=letterbook
    steps:
      - name: Test database connection 
        run: apt-get update -qq; apt-get install -y -qq postgresql-client; PGPASSWORD=letterbookpw psql -h localhost -U postgres -c '\dt' test
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      #- run: dotnet build Letterbook.sln 
      - name: Test
        if: false
        run: dotnet test Letterbook.UnitTests.slnf --configuration Release --logger console
      - name: Integration tests
        run: bash ./scripts/integration-test.sh # ${{ github.event.inputs.dotnet-test-args }} 