on: [push]
jobs:
  test:
    runs-on: codeberg-medium # https://codeberg.org/actions/meta#available-runners
    services:
      timescale:
        image: timescale/timescaledb:2.17.2-pg15-oss
        environment:
          - POSTGRES_USER=letterbook
          - POSTGRES_PASSWORD=letterbookpw
          - POSTGRES_DB=letterbook_feeds
        ports:
          - "5433:5433"
        volumes:
          - ts_data:/var/lib/postgresql/data
      pgsql:
        image: postgres:16-alpine
        command:
          - postgres
          - -c
          - config_file=/etc/postgresql/postgresql.conf
        environment:
          - POSTGRES_USER=letterbook
          - POSTGRES_PASSWORD=letterbookpw
          - POSTGRES_DB=letterbook
        ports:
          - "1337:1337"
        volumes:
          - db_data:/var/lib/postgresql/data
          - ./volumes/postgresql.conf:/etc/postgresql/postgresql.conf:z
          - ./volumes/pg_hba.conf:/etc/postgresql/pg_hba.conf:z
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      #- run: dotnet build Letterbook.sln 
      - name: Test
        run: dotnet test Letterbook.UnitTests.slnf --configuration Release --logger console
      # - name: Set up Docker Compose
      #   uses: docker/setup-compose-action@v1
      # Not sure how to do this
      # - name: Start database
      #   run: bash scripts/start-database.sh
      # - name: Integration tests
      #   run: bash scripts/integration-test.sh # ${{ github.event.inputs.dotnet-test-args }} 