# https://forgejo.org/docs/next/user/actions/reference/#onworkflow_dispatch
on: [push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: codeberg-medium # https://codeberg.org/actions/meta#available-runners
    services:
      timescale:
        image: timescale/timescaledb:2.17.2-pg15-oss
        env:
          POSTGRES_USER: letterbook
          POSTGRES_PASSWORD: letterbookpw
          POSTGRES_DB: letterbook_feeds
        # These ports are ignored. Each service is automatically hosted at different address.
        #
        #   "The IP address of pgsql is on the same network as the container running the steps and there is no need for port binding."
        #
        # https://forgejo.org/docs/latest/user/actions/advanced-features/#services 
        #
        # ports: 
        #   - "5433:5432"
      pgsql:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: letterbook
          POSTGRES_PASSWORD: letterbookpw
          POSTGRES_DB: letterbook
    steps:
      - name: Test database connection 
        if: false
        run: apt-get update -qq; apt-get install -y -qq postgresql-client; PGPASSWORD=letterbookpw psql -h pgsql -U letterbook -c '\dt' letterbook
      - name: Test timescale database connection 
        if: false
        run: PGPASSWORD=letterbookpw psql -h timescale -U letterbook -c '\dt' letterbook_feeds
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet build Letterbook.sln 
      - name: Unit test
        if: false # Fails weirdly for some reason
        run: dotnet test Letterbook.UnitTests.slnf --configuration Release --logger console --no-restore --no-build
      - name: Core test
        run: dotnet test Tests/Letterbook.Core.Tests/ --no-restore --no-build
      - name: Integration test
        env:
          ConnectionStringHost: pgsql
          FeedsConnectionStringHost: timescale
          FeedsConnectionStringPort: 5432
        run: bash ./scripts/integration-test.sh --no-build --no-restore # ${{ github.event.inputs.dotnet-test-args }} 