on: [push]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet build Letterbook.sln 