on: [push]
jobs:
  test:
    runs-on: codeberg-medium # https://codeberg.org/actions/meta#available-runners
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      #- run: dotnet build Letterbook.sln 
      - name: Test
        run: dotnet test Letterbook.UnitTests.slnf --configuration Release --logger GitHubActions
      # - name: Set up Docker Compose
      #   uses: docker/setup-compose-action@v1
      # Not sure how to do this
      # - name: Start database
      #   run: bash scripts/start-database.sh
      # - name: Integration tests
      #   run: bash scripts/integration-test.sh # ${{ github.event.inputs.dotnet-test-args }} 