# https://forgejo.org/docs/next/user/actions/reference/#onworkflow_dispatch
on: [push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: codeberg-medium # https://codeberg.org/actions/meta#available-runners
    services:
      timescale:
        image: timescale/timescaledb:2.17.2-pg15-oss
        env:
          POSTGRES_USER: letterbook
          POSTGRES_PASSWORD: letterbookpw
          POSTGRES_DB: letterbook_feeds
        # ports: # I think these are ignored so
        #   - "5433:5432"
      pgsql:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: letterbook
          POSTGRES_PASSWORD: letterbookpw
          POSTGRES_DB: letterbook
    steps:
      - name: Test database connection 
        run: apt-get update -qq; apt-get install -y -qq postgresql-client; PGPASSWORD=letterbookpw psql -h pgsql -U letterbook -c '\dt' letterbook
      - name: Test timescale database connection 
        run: PGPASSWORD=letterbookpw psql -h timescale -U letterbook -c '\dt' letterbook_feeds
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      #- run: dotnet build Letterbook.sln 
      - name: Test
        if: false
        run: dotnet test Letterbook.UnitTests.slnf --configuration Release --logger console
      - name: Integration tests
        env:
          ConnectionStringHost: pgsql
          FeedsConnectionStringHost: timescale
          FeedsConnectionStringPort: 5432
        run: bash ./scripts/integration-test.sh # ${{ github.event.inputs.dotnet-test-args }} 