# REST templates for Letterbook's first-party APIs

### Draft and publish
POST {{host}}/lb/v1/posts/{{profileId}}/post
Content-Type: application/json

{
  "id": "{{profileId}}",
  "summary": "Draft and publish",
  "creators": [
    {
      "id": "{{profileId}}"
    }
  ],
  "contents": [
    {
      "sortKey": 0,
      "type": "Note",
      "text": "Simple text post from Api.http"
    }
  ],
  "audience": [],
  "addressedTo": [],
  "repliesCollection": [],
  "likesCollection": [],
  "sharesCollection": []
}

### Follow FediId
POST {{host}}/lb/v1/profiles/{{id}}/
