# REST templates for Letterbook's first-party APIs

### Draft and publish
POST {{host}}/lb/v1/posts/{{profileId}}/post
Content-Type: application/json

{
  "id": "{{profileId}}",
  "summary": "Draft and publish",
  "creators": [
    {
      "id": "{{profileId}}"
    }
  ],
  "contents": [
    {
      "type": "Note",
      "text": "Posted from Api.http"
    }
  ],
  "audience": [
    {
      "fediId": "https://www.w3.org/ns/activitystreams#Public"
    }
  ],
  "addressedTo": []
}

### Follow FediId
GET {{host}}/lb/v1/profiles/{{profileId}}/

### Query Peer
GET {{host}}/lb/v1/profiles?handle={{peer_user}}