### Get Actor
GET {{host}}/actor/{{actor_id}}
Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"

### Get Peer Actor
GET {{peer_actor}}
Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"


### Webfinger Peer
GET {{peer}}/.well-known/webfinger?resource=acct:@{{peer_user}}@{{peer_domain}} 

