// <auto-generated />
using System;
using Letterbook.Adapter.TimescaleFeeds;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Letterbook.Adapter.TimescaleFeeds.Migrations
{
    [DbContext(typeof(FeedsContext))]
    [Migration("20230829033607_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Letterbook.Adapter.TimescaleFeeds.Entities.Entry", b =>
                {
                    b.Property<string>("AudienceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudienceName")
                        .HasColumnType("text");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoostedBy")
                        .HasColumnType("text");

                    b.Property<string[]>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("AudienceKey");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AudienceKey"), "Hash");

                    b.HasIndex("Authority");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Authority"), "Hash");

                    b.HasIndex("CreatedBy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CreatedBy"), "GIN");

                    b.HasIndex("EntityId");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EntityId"), "Hash");

                    b.HasIndex("Time");

                    b.ToTable("Feeds");
                });
#pragma warning restore 612, 618
        }
    }
}
