//HintName: TestIdIntEfConverter.g.cs
// <auto-generated from Letterbook.Generators.TypedIdGenerator/>

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Letterbook.Generators;

namespace Letterbook.Generators.Tests;

[TypedIdEfConverter<TestIdInt>]
public class TestIdIntEfConverter : ValueConverter<TestIdInt, int>
{
    public TestIdIntEfConverter() : base(id => id.Id, value => new(value)) { }
}