//HintName: TestIdIntSwaggerSchemaFilter.g.cs
// <auto-generated from Letterbook.Generators.TypedIdGenerator/>

using Letterbook.Generators;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Letterbook.Generators.Tests;

public class TestIdIntSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        schema.Type = "integer";
        schema.Properties = null;
        schema.Example = new OpenApiString(default(TestIdInt).ToString());
    }
}