//HintName: TestIdUuidJsonConverter.g.cs
// <auto-generated from Letterbook.Generators.TypedIdGenerator/>

using System.Text.Json;
using System.Text.Json.Serialization;
using Letterbook.Generators;
using Medo;

namespace Letterbook.Generators.Tests;

[TypedIdJsonConverter]
public class TestIdUuidJsonConverter : JsonConverter<TestIdUuid>
{
    /// <inheritdoc />
    public override TestIdUuid Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
   		try
   		{
   			var value = JsonSerializer.Deserialize<Uuid7>(ref reader, options);
   			return new TestIdUuid(value);
   		}
   		catch (Exception e)
   		{
   			throw new JsonException("Unable to convert to TestIdUuid", e);
   		}
    }

    /// <inheritdoc />
    public override void Write(Utf8JsonWriter writer, TestIdUuid value, JsonSerializerOptions options)
    {
          JsonSerializer.Serialize(writer, value.Id, options);
    }
}