//HintName: TestIdUuid.g.cs
// <auto-generated from Letterbook.Generators.TypedIdGenerator/>

using System.ComponentModel;
using Swashbuckle.AspNetCore.Annotations;
using Medo;

namespace Letterbook.Generators.Tests
{
    [SwaggerSchemaFilter(typeof(TestIdUuidSchemaFilter))]
    [TypeConverter(typeof(TestIdUuidConverter))]
    partial record struct TestIdUuid : Letterbook.Generators.ITypedId<Uuid7>
    {
        public override string ToString() => Id.ToId25String();
        public static Uuid7 FromString(string s) => Uuid7.FromId25String(s);

        public static explicit operator Uuid7(TestIdUuid id) => id.Id;
        public static implicit operator TestIdUuid(Uuid7 id) => new TestIdUuid(id);
    }
}