//HintName: TestIdInt.g.cs
// <auto-generated from Letterbook.Generators.TypedIdGenerator/>

using System.ComponentModel;
using Swashbuckle.AspNetCore.Annotations;


namespace Letterbook.Generators.Tests
{
    [SwaggerSchemaFilter(typeof(TestIdIntSchemaFilter))]
    [TypeConverter(typeof(TestIdIntConverter))]
    partial record TestIdInt : Letterbook.Generators.ITypedId<int>
    {
        public override string ToString() => Id.ToString();
        public static int FromString(string s) => int.Parse(s);

        public static explicit operator int(TestIdInt id) => id.Id;
        public static implicit operator TestIdInt(int id) => new TestIdInt(id);
    }
}