//HintName: TestIdUuidEfConverter.g.cs
// <auto-generated from Letterbook.Generators.TypedIdGenerator/>

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Letterbook.Generators;

namespace Letterbook.Generators.Tests;

[TypedIdEfConverter<TestIdUuid>]
public class TestIdUuidEfConverter : ValueConverter<TestIdUuid, Guid>
{
    public TestIdUuidEfConverter() : base(id => id.Id.ToGuid(), value => new(new Medo.Uuid7(value))) { }
}